### ISSUE TITLE
new scripts path different for latest nexus version

### ISSUE THREAD

**Issue by cbanciu667** [ansible-ThoTeam/nexus3-oss#110]
Hi,

I get the following error for nexus 3.13.x:
`fatal: [nexus01]: FAILED! => {"changed": false, "connection": "close", "content": "", "date": "Tue, 11 Sep 2018 06:46:25 GMT", "msg": "Status code was 401 and not [204, 404]: HTTP Error 401: Unauthorized", "redirected": false, "server": "Nexus/3.13.0-01 (OSS)", "status": 401, "url": "http://localhost:8081/service/rest/v1/script/setup_capability", "www_authenticate": "BASIC realm=\"Sonatype Nexus Repository Manager\"", "x_content_type_options": "nosniff"}`

Similar errors are present for all scripts and the reason is the PATH of the API after version 3.8.x:
https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api/managing-and-running-scripts

Can you please parameterise the API path so it can be changed from vars ?

Thank you.
Cosmin

**Comment by zeitounator** [comment]
Hi,

This problem as already been addressed. If you look carefully, the url that reports an error **is** the url for nexus > 3.8. (it was /service/siesta/rest/v1/script previously). The role detects which version you are using and will adapt the path accordingly.

My guess: you are upgrading nexus with the role and, for some reason, nexus was not restarted during the process. In this case, the role thinks it is interacting with v>=3.8 while you are still running version v<3.8.

Which version of the role are you running ? I recently fixed an issue where nexus would not get restarted on some events. You might be hitting this case.

Let me know if you could fix the problem.

**Comment by zeitounator** [comment]
I may have an other explanation actually. Didn't look carefully at the HTTP return code wich states "401 unauthorized". This looks like an admin password problem. Double check the password you're passing to the role.

**Comment by cbanciu667** [comment]
Hi,

I checked the password but is seems it is not the reason. I can login with the password from vars.

Version is 3.13.0-01 as you can see bellow.
If i understand correctly the nexus article i have given above the path should be: 
http://localhost:8081/service/siesta/rest/v1/script/update_admin_password/run
Nevertheless i get 404 for that one too.

After activating admin password option in vars i get: 
fatal: [nexus01]: FAILED! => {"changed": false, "connection": "close", "content": "", "date": "Tue, 11 Sep 2018 07:57:44 GMT", "msg": "Status code was 404 and not [200, 204]: HTTP Error 404: Not Found", "redirected": false, "server": "Nexus/3.13.0-01 (OSS)", "status": 404, "url": "http://localhost:8081/service/rest/v1/script/update_admin_password/run", "x_content_type_options": "nosniff", "x_siesta_faultid": "914acef2-f644-4bd6-9a7d-ce19255ea3dd"}

**Comment by cbanciu667** [comment]
I am running the ansible playbook from a separate Jenkins instance. 
I will try to copy it directly on the nexus instance and run it there.

**Comment by zeitounator** [comment]
Now it is a different error => 404. Can you please make sure the <nexus-data>/groovy-raw-scripts is empty on the target machine and run the role again ?

**Comment by cbanciu667** [comment]
I cleared <nexus-data>/groovy-raw-scripts directory and it worked :)
It ran end to end without issues.

Many thanks!

**Comment by zeitounator** [comment]
Glad to hear that ! I'm currently adding a maintenance feature to ease that process for maintenance/debug scenario as the one you just experienced. Will release today.

**Comment by zeitounator** [comment]
New feature is currently tested in #111

**Comment by zeitounator** [comment]
Just merged branch #111 with this new feature in cas you need it again. Cheers !
