### ISSUE TITLE
Support SSLCertificateChainFile

### ISSUE THREAD

**Issue by martypitt** [ansible-ThoTeam/nexus3-oss#121]
I used this role to configure my nexus instance, secured with a letsencrypt certificate

However, when trying to deploy, I got errors similar to:

```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Note, I'm using java8 1.8.0_171, [which does support letsencrypt certificates](https://letsencrypt.org/docs/certificate-compatibility/)

Turns out that the issue was the apache proxy needs to be configured with the SSLCertificateChainFile.

[Stackoverflow post describing solution](https://stackoverflow.com/a/45801793/59015) and related [letsencrypt community post](https://community.letsencrypt.org/t/solved-why-isnt-my-certificate-trusted/2479) confirming which file to use.

As described in those posts, the fix was simple to apply, I just edited my apache2 config at `/etc/apache2/sites-enabled/{mySite}`
as follows:

```
  SSLCertificateFile /etc/letsencrypt/live/mysite/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/mysite/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/mysite/chain.pem <--- Added this line
  ServerName mysite
  ServerAdmin admin@example.com
```

However, now my server is a snowflake.

Would be awesome if I could specify this along with the other certs in the role.  ie:

```
    httpd_ssl_cert_file_location: "/etc/letsencrypt/live/{{public_hostname}}/cert.pem"
    httpd_ssl_cert_key_location: "/etc/letsencrypt/live/{{public_hostname}}/privkey.pem"
    httpd_ssl_cert_chain_location: "/etc/letsencrypt/live/{{public_hostname}}/chain.pem"
```

**Comment by zeitounator** [comment]
Hi @martypitt. First of all, thanks for your sharing and sorry for the delay to respond.

The apache reverse proxy configuration in this role is actually very basic with very few possibilities to override the defaults. In my own usual use, I actually turn off apache configuration in the role and then create a custom role inheriting from this one to deploy more complex reverse proxy configs on specific network environments.

Meanwhile, you suggestion is easy to implement and would benefit everybody still needing a basic reverse proxy config. I will try to release that soon.
