### ISSUE TITLE
Synchronizing groovy scripts silently fails if rsync is not installed on the target machine

### ISSUE THREAD

**Issue by pyranja** [ansible-ThoTeam/nexus3-oss#122]
I'm using this role to build an AMI. When using the latest Amazon Linux 2 AMI as base, synchronizing the groovy scripts fails, because `rsync` is not installed by default.

```
    amazon-ebs: TASK [ansible-thoteam.nexus3-oss : Sync new scripts to old and get differences] ***
    amazon-ebs: ok: [default] => {"changed": false, "cmd": "rsync -ric /var/nexus/groovy-raw-scripts/new/ /var/nexus/groovy-raw-scripts/current/ | cut -d\" \" -f 2 | sed \"s/\\.groovy//g\"", "delta": "0:00:00.003462", "end": "2018-10-19 01:26:19.553477", "rc": 0, "start": "2018-10-19 01:26:19.550015", "stderr": "/bin/sh: rsync: command not found", "stderr_lines": ["/bin/sh: rsync: command not found"], "stdout": "", "stdout_lines": []}
```

Unfortunately the sync task does *not* fail and provisioning continues without groovy scripts. Eventually the execution fails with 404 HTTP responses.

```
    amazon-ebs: TASK [ansible-thoteam.nexus3-oss : Calling Groovy script update_admin_password] ***
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "connection": "close", "content": "", "date": "Fri, 19 Oct 2018 01:26:21 GMT", "msg": "Status code was 404 and not [200, 204]: HTTP Error 404: Not Found", "redirected": false, "server": "Nexus/3.14.0-04 (OSS)", "status": 404, "url": "http://localhost:8080/service/rest/v1/script/update_admin_password/run", "x_content_type_options": "nosniff", "x_siesta_faultid": "3c9f488d-febc-49e5-b3b8-176488f167dd"}
```

I can of course work around this by installing rsync beforehand.

Nonetheless I think it does make sense to ensure that required tooling is present on the target.

**Comment by zeitounator** [comment]
Hi @pyranja and thanks for your feedback.

This is due to the fact that the shell command return code is the one of the last command in the pipe. Although it is definitelly a good idea to check that rsync is installed as a prerequesite, I'll still try to fix this so that we can capture other possible rsync errors. Basically, we need to fail this task if any of the commands in the pipe does not return 0.

Will try to release that soon.

**Comment by bbd08unlimited** [comment]
I just had this issue.  Running centos 7 minimal. But mine did not fail until it tried running the scripts on nexus. A quick check for rsync being present would solve this.

**Comment by zeitounator** [comment]
I just upated the molecule and ansible-lint version used to build the role. There is a new check in ansible-lint => "shell that use pipe should set the pipefail option". Obeying this rule lead to a change on the incriminated task which will now fail verbosely if rsync is not installed or fires any kind of error in the pipe command.

I keep the issue opened and will add a check for rsync as suggested with an appropriate fail msg.

Cheers.
