### ISSUE TITLE
Provisioning fails when using nexus3-oss role with packer from Mac OSX

### ISSUE THREAD

**Issue by nishant009** [ansible-ThoTeam/nexus3-oss#137]
Hello,

I am getting an error running the `nexus3-oss` role. I am trying to install `nexus` repository on an `EC2` instance provisioned using `packer`.

#### Error Details
The error I'm getting is coming from the invocation of [this](https://github.com/ansible-ThoTeam/nexus3-oss/blob/7c2c39987b865378933fb54220a02ee451254066/tasks/nexus_install.yml#L432) task that is part of the `nexus3-oss` role. Below is the dump of error output:
```
amazon-ebs: TASK [ansible-ThoTeam.nexus3-oss : Archive scripts] ****************************
amazon-ebs: fatal: [default -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
It seems that the task is trying to package all the `groovy` scripts that ship with the role into a `tar` file so that they can be uploaded to the remote machine where `nexus` is being installed. To this end its trying to write the `tar` file at the location `/tmp/.` In `macOS X 10.14.2` `/tmp` is a symlink with the following permissions:
```
0 lrwxr-xr-x@ 1 root  wheel    11B 17 Dec 15:43 /tmp -> private/tmp
```
Since I'm running `ansible` role through `packer`, it fails writing to this directory.

#### Workaround
I can run packer with `sudo` and it would succeed but I believe I shouldn't need to use `sudo`.

#### System Details
I have `macOS X 10.14.2 (18C54)` on my machine (host) that is running `Ansible V2.7.5` and `Packer V1.3.3`. The provisioned `EC2` instance (remote) on which `nexus` is being installed has `Debian GNU/Linux 9 (stretch)` as its OS.

#### Code
Here is a link to my [nexus](https://gist.github.com/nishant009/86cb1558916ff5850e9020ca47fcc9c8) playbook as well as a link to my [packer](https://gist.github.com/nishant009/cb6a9e143fb76fd277943ed3425465cb) file.

**Comment by zeitounator** [comment]
What are the permissions on the target repository private/tmp ? The permission you reported are the one of your symbolic link.

It looks like this is somewhat a known issue for Mac users: https://www.iexplain.org/macos-operation-not-permitted-tmp-not-writable/

/tmp is expected to be world writable by anyone on a *nix" system.

**Comment by zeitounator** [comment]
@nishant009 Where you able to fix the problem with the above informations ?

**Comment by zeitounator** [comment]
Closing since I didn't get any update. Feel free to reopen if needed.
