### ISSUE TITLE
Playbook hang when running install of Nexus PRO

### ISSUE THREAD

**Issue by nicosto** [ansible-ThoTeam/nexus3-oss#138]
Hi,

The handler "wait-for-nexus" regexp on the string "Started Sonatype Nexus OSS .*"
unfortunately the valid string if run against a Nexus PRO is "Started Sonatype Nexus PRO .*

Changing the test for "Started Sonatype Nexus .*" will allow to support both version.
Cheers,
Nicolas

**Comment by zeitounator** [comment]
Hi,

As its name suggest, this role is meant to install nexus **OSS** version, not the pro version.

Where you able to install and use the pro version with the role after changing the searched regex ? If this is the only step failing, as it is very easy and safe to fix, I will change it for the next release. But I will not fix any other issue that would arise when using the pro version (accept license, etc....).

**Comment by nicosto** [comment]
Hi, 
 I confirm this is only the regex that block on the restart of nexus PRO when the playbook is played. 

As you stated this is for the OSS version of nexus and I'm not looking to have PRO features.
