### ISSUE TITLE
Problem with maven group repo creation on update of installation

### ISSUE THREAD

**Issue by clydet** [ansible-ThoTeam/nexus3-oss#139]
There's a problem when rerunning the role against an existing installation where the role attempts setup the default maven group repo. Why isn't this governed by `nexus_delete_default_repos`?

https://github.com/ansible-ThoTeam/nexus3-oss/blob/7c2c39987b865378933fb54220a02ee451254066/defaults/main.yml#L260

**Comment by zeitounator** [comment]
What is the exact problem you are getting ?

As the path suggests, these are default values. You should change them to adapt to your needs. As a basic start, if you don't want to configure any maven group repository, `nexus_repos_maven_group: []` should fix your problem

**Comment by zeitounator** [comment]
@clydet Any news on this one ?

**Comment by zeitounator** [comment]
Closing since I didn't get any update. Feel free to reopen if needed.
