### ISSUE TITLE
Nexus 3.8  will have a new URL for Rest API calls

### ISSUE THREAD

**Issue by dannyk81** [ansible-ThoTeam/nexus3-oss#14]
We should be aware of the planned change, described in this PR https://github.com/sonatype/nexus-book-examples/pull/20 and in [NEXUS-14940](https://issues.sonatype.org/browse/NEXUS-14940) ticket.

It seems to be targeted for some Nexus 3.7.x version (later than 3.7.0), the URL for the REST API will change from `service/siesta/...` to `service/rest/...`

I believe this will only affect the following:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/5d5503225b0dc290b6a23ba6cf33f3c76e345377/tasks/call_script.yml#L4
https://github.com/ansible-ThoTeam/nexus3-oss/blob/5d5503225b0dc290b6a23ba6cf33f3c76e345377/tasks/declare_script_each.yml#L4
https://github.com/ansible-ThoTeam/nexus3-oss/blob/5d5503225b0dc290b6a23ba6cf33f3c76e345377/tasks/declare_script_each.yml#L13

**Comment by zeitounator** [comment]
Hi @dannyk81. Thanks for pointing this out. I've been looking around but did not find any potential release date for v3.7. If you have any idea, let me know. I'll try to follow up and test early if I can find an rc version before final release. From what I understand, the change should be quite trivial.

**Comment by zeitounator** [comment]
https://github.com/sonatype/nexus-book-examples/pull/20#issuecomment-351748553

Changes will be incorporated later in time (not 3.7.0). Updated ticket title and description.

**Comment by dannyk81** [comment]
Yep, looks like this was delayed.

We'll keep an 👁 on it

**Comment by samherve** [comment]
Looks like 3.7.1 is out : https://help.sonatype.com/display/NXRM3/2017+Release+Notes#id-2017ReleaseNotes-RepositoryManager3.7.1 ! Also, I confirm (from docker image https://hub.docker.com/r/sonatype/nexus3/, version 3.7.1-02) that the old endpoints don't work anymore

**Comment by dannyk81** [comment]
Are you sure? according to this (https://issues.sonatype.org/browse/NEXUS-14940) the change is intergated into 3.8.0

**Comment by samherve** [comment]
I'll triple-check and come back with a confirmation.

**Comment by zeitounator** [comment]
The latest role version is installing 3.7.1-02 by default and all test are passing on travis. I'm using it on production.

**Comment by dannyk81** [comment]
3.8 is [out](https://help.sonatype.com/display/NXRM3/2018+Release+Notes#id-2018ReleaseNotes-RepositoryManager3.8.0) 😄 

```
REST API deprecating /siesta
The "/service/siesta/rest/v1/script" endpoint has been moved to "/service/rest/v1/script".
NEXUS-14940
```

**Comment by zeitounator** [comment]
As you can see above in the activity, this is implemented on the dev_2.1 branch. Release pending. A single ticket left in the corresponding project: https://github.com/ansible-ThoTeam/nexus3-oss/projects/2
