### ISSUE TITLE
Problems with Java 8 requirements (License)

### ISSUE THREAD

**Issue by rcmoutinho** [ansible-ThoTeam/nexus3-oss#140]
In the case of using a RedHat installation and the [oracle-java](https://github.com/ansiblebit/oracle-java) ansible role, there is an issue on trying to accept Java license.

Here are more details about it:
https://github.com/ansiblebit/oracle-java/issues/108

Any clue about the approach to solving it?

**Comment by zeitounator** [comment]
Hi,

As stated in the conversation mentionned above, you should consider switching to openjdk. I've been running several production installation for months without any problem. Sonatype will soon announce they are officially supporting it before oracale java 8 reaches eol: https://community.sonatype.com/t/support-for-openjdk/893.

Cheers.

**Comment by zeitounator** [comment]
Hi @rcmoutinho. Please see related #149. Sonatype is now officially recommending openjdk8

**Comment by rcmoutinho** [comment]
Thanks for the update @zeitounator!
