### ISSUE TITLE
Run against kubernetes deployed Nexus

### ISSUE THREAD

**Issue by rhnewtron** [ansible-ThoTeam/nexus3-oss#153]
Hi, 

we are using the official docker image of nexus3 to run nexus on Openshift. As this only solved the "installation" of Nexus3 and not the configuration, I would like to use this playbook for setting up nexus via groovy only. 

Is this possible (similar to nexus_run_provisionning: false but other way around ) ?

**Comment by zeitounator** [comment]
Hi,

This is not possible for time being. Skipping install would not work: the role needs to know where nexus is installed and how it is configured, so it it should check all this before provisioning. This was not designed with a nexus prebuilt image in mind and would require quite a bit of work that I cannot cope with at the moment.
