### ISSUE TITLE
nexus_public_hostname vs httpd_server_name

### ISSUE THREAD

**Issue by devantoine** [ansible-ThoTeam/nexus3-oss#157]
Hi,

I've faced an issue with Nexus not being accessible through the httpd reverse proxy.

After a quick look there's two `ServerName` directives set in the SSL virtual host : the first one uses `httpd_server_name` while the second one uses `nexus_public_hostname`.

The log file's names use `nexus_public_hostname`.

The doc mentions both variables.

Is there a reason to keep them both or is it something missed in a previous refactoring?

Anyway, thanks for what you're doing, keep up the good work 👏

**Comment by zeitounator** [comment]
Hi devantoine,

I didn't dig into the reverse proxy setup part for quite a while as I actually don't use it much. I usually deploy nexus in particular client's environment with so many specificities that it is easier to deactivate that part and create a custom child role to deploy the reverse proxy (several docker private registries, custom redirects depending on source ip calling, etc....)

My first thought is that we should not have different variables for the same use and that this is probably a leftover of a not-so-well-tested refactoring or enhancement. I'll have a look when I get a chance and come back with an answer.

Anyhow, thanks for your interest.

**Comment by devantoine** [comment]
@zeitounator I think only one of them should remain and it's coming from a "not-so-well-tested" refactoring.

Just looking at the Virtual Host directive for port 443 can tell you it's a bug : you shouldn't have two `ServerName` directives in the same block.

**Comment by zeitounator** [comment]
Since my client did not anticipate my contract renewal, I'm getting some cool time to work on this at home.

You're definitely right, it's a bug. My apologies for probably being drunk when I accepted this back in October 2017: https://github.com/ansible-ThoTeam/nexus3-oss/pull/5/commits/e8872c40b987caec38d800e2fe3689a87c4d2ebd

This is just a proof that this part of the role is almost never used or I would have got a bug report earlier. I'm not really surprised as this is a really basic reverse proxy setup and not really customizable. I might drop this is a future release (and eventually release a companion role with more flexibility, as I already do privately for clients).

For time being, I'll keep this as is and I'm going to release a fix in the next couple hours max. Will you survive until then ?

**Comment by zeitounator** [comment]
Hmmm, this is trickier than I thought and my assumption about people not using the feature might be wrong. The reverse proxy is actually deployed on every CI run on travais and it is working as expected, at least in the testinfra cases in molecule. So having to servernames does not prevent apache from responding and is screwing things up only in certain situations (probably when your set httpd_server_name). Anyway, fix on launchad.

**Comment by devantoine** [comment]
@zeitounator I'm ok, I've already edited the role ;)

**Comment by devantoine** [comment]
@zeitounator Yes, in fact you could have multiple `ServerName` directive in the same block, it's just the last one which wins.

It may be a really simple reverse proxy but it's what I set (before knowing this role) at every client I work for.

I want Nexus to be accessible through 80 (for the redirection) and 443 and setting Apache to hold the SSL certificate is easier in my opinion.

**Comment by zeitounator** [comment]
Now you still have nexus_public_name and httpd_servername, but they are clearly documented, the later defaults to the first if you omit it and there is a single ServerName directive in the resulting httpd file.

Thanks for your report.

**Comment by devantoine** [comment]
What's the point of keeping them both?

**Comment by zeitounator** [comment]
If for whatever reason you need the nexus installation name to be different from the apache reverse proxy name. If you don't use httpd_servername, it will default to nexus_public_hostname

**Comment by devantoine** [comment]
I see.

Thanks for your work.
