### ISSUE TITLE
S3 Blob Store

### ISSUE THREAD

**Issue by sdollins** [ansible-ThoTeam/nexus3-oss#160]
I'm having a rough time getting the S3 blobstore integration to work.

`fatal: [127.0.0.1]: FAILED! => {"changed": false, "connection": "close", "content": "{\n  \"name\" : \"create_blobstores_from_list\",\n  \"result\" : \"javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: msg for class: Script5\"\n}", "content_length": "169", "content_type": "application/json", "date": "Mon, 15 Apr 2019 22:37:56 GMT", "json": {"name": "create_blobstores_from_list", "result": "javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: msg for class: Script5"}, "msg": "Status code was 400 and not [200, 204]: HTTP Error 400: Bad Request", "redirected": false, "server": "Nexus/3.16.0-01 (OSS)", "status": 400, "url": "http://localhost:8081/service/rest/v1/script/create_blobstores_from_list/run", "x_content_type_options": "nosniff"}`

From my playbook:

`      nexus_blobstores:
        - name: s3
          type: S3
          config:
            bucket: infra-sonatype-s3`

I'm not quite sure what to test next. I've tried a few different variations and ensured my EC2 instance has a role attached to use S3.

**Comment by zeitounator** [comment]
Which version of the role are you using ? Latest ? I started refactoring some of the groovy scripts. The S3 config was a contribution from a user and I currently have no direct way to test this. I might have done something wrong during this refactoring that pops up only when configuring s3 blobstores (at least it looks like it from the error message).

Can you test with a previous version of the role and see if it solves your problem ? I suggest you try with https://github.com/ansible-ThoTeam/nexus3-oss/releases/tag/v2.3.1

I have some ongoing work to continue the refactoring work on the scripts and enhanced the returns. I will check what is going on (which is probably only a var declaration problem).

Thanks for your collaboration.

**Comment by sdollins** [comment]
I was indeed using the latest.

I pinned it to v2.3.1 and it's working just fine.

I am building an AMI regularly so I'm happy to keep testing this for you.

**Comment by zeitounator** [comment]
Glad to hear that and thanks for your implication !! I'll comment here when I have something ready to test.

**Comment by zeitounator** [comment]
Hi @sdollins,

Could you please checkout the branch from the PR #165 and tell me if it fixes your issue ?

From what I could see, you were getting the above message because the script could not create your blobstore for some reason and was later getting a second error when trying to log info into nexus run log. If you still get errors, can you please report them in the PR ? It will be easier to keep track of what is going on. Thanks a million.
