### ISSUE TITLE
S3 Blob Store config w/ custom endpoints

### ISSUE THREAD

**Issue by unim21** [ansible-ThoTeam/nexus3-oss#163]
I've been going over the defaults.yml and I've been unable to find the equivalent of GUI's "Endpoint URL (Optional)" field for configuring a 3rd party object store via Ansible.  I've successfully implemented this via the GUI and it works fine, but I need to be able to do it via Ansible (hopefully like so)

` - name: s3-blobstore`
`   type: S3`
 `  config:`
 `    bucket: s3-blobstore`
`     accessKeyId: "{{ VAULT_ENCRYPTED_KEY_ID }}"`
 `    secretAccessKey: "{{ VAULT_ENCRYPTED_ACCESS_KEY }}"`
  `   endpointURL: some.s3.url.com` <--- what I need to add

Am I missing something here?  Is there a way to add this field into the S3 blobstore creation config in the defaults file and have it parse correctly? 

Also, it doesn't seem to be attempting to create the blobstore at all - I'm not seeing any tasks in the log for it or any errors. Any advice here would be greatly appreciated!

I'm using the latest version of the role installed via ansible-galaxy.

**Comment by zeitounator** [comment]
Hi and thanks for your interest. Please note the following sentence in the doc

> Configuring blobstore on S3 is provided as a convenience and is not part of the automated tests we run on travis. Please note that storing on S3 is only recommended for instances deployed on AWS.

In other words: I do not have any access to AWS to test S3 blobstore creation at any stage.

That being said:
1. there is currently a bug (#160) on the latest version preventing to create s3 blobstores that I should get fixed shortly. In the mean time, you can use the previous version of the role (v2.3.1)
3. technically, creating an s3 blobstore in groovy is as simple as https://github.com/ansible-ThoTeam/nexus3-oss/blob/7ec19ba9088f1653e07d892b41c0d61b17e49658/files/groovy/create_blobstores_from_list.groovy#L18
So anything you add to the `config` hash in your vars will be passed to the groovy function. You just need to find the corresponding parameter names to use them as keys and it should work. I'll try to spend some time adding those to the documentation once I get the above bug fixed.

**Comment by zeitounator** [comment]
From my first search, it looks like the parameter name your are looking for is `endpoint`.

**Comment by zeitounator** [comment]
Closed since there was no feedback.
