### ISSUE TITLE
Relocate nexus_tmp_dir on RedHat

### ISSUE THREAD

**Issue by gbonnefille** [ansible-ThoTeam/nexus3-oss#168]
By default, `nexus_tmp_dir` is set to `/tmp/nexus`.

This setting is good on Debian based system as this directory is cleaned on reboot.
But on RedHat, this directory is cleaned regularly by systemd.

One solution could be to configure systemd by declaring `/tmp/nexus` as an exclusion. But this induce heavy-coupled script with systemd.

Another solution, simpler, is to define an other default for RedHat based system (perhaps `/var/nexus-tmp`).

If you agree with such improvment, I can prepare and push a pull-request.

**Comment by zeitounator** [comment]
Hi and thanks for this feature request.

My initial view was that being able to set `nexus_tmp_dir` to user's will was enough but I'm always opened to suggestions.

I'd be happy to accept a PR as long as it is fully backward compatible and fits nicely in the job already done. You will probably want to have a look at the existing OS specific files in the `vars` directory and [how they are loaded](https://github.com/ansible-ThoTeam/nexus3-oss/blob/4995a154f02bd1ff138c168cd5f1c5b6ac7be61b/tasks/main.yml#L9)

I think the best way to implement this is to make `nexus_tmp_dir` optionnal (undefined) in `defaults/main.yml` and use the default value loaded from the above file unless the user defined a value to override. Of course, these changes need to be reported in documentation.

Was it globally your view of the implementation of this feature or do you think we need to discuss further ?

Looking forward to hear from you, Cheers ! Et merci beaucoup !

**Comment by gbonnefille** [comment]
Sorry, I was unable to work on this issue. Thanks for solving it. :+1:
