### ISSUE TITLE
Add kar bundle plugin support

### ISSUE THREAD

**Issue by marchenm** [ansible-ThoTeam/nexus3-oss#169]
Thanks to some upstream work in Nexus Repository (versions newer than 3.15), it's become a LOT easier to install a plugin. 

Simply copy the bundle.kar file to the `deploy` folder for your Nexus Repository installation and restart Nexus. 

A simple `get_url` or `copy` should install the plugins.

**Comment by zeitounator** [comment]
Hi ! This looks really interesting. Do you happen to have any sort of documentation on this process ?

I didn't find anything in [the documenation related to bundles](https://help.sonatype.com/repomanager3/bundle-development/installing-bundles#app). I also went through some plugins I know (apt, helm...) in [sonatype community](https://github.com/sonatype-nexus-community) and didn't find any documenting this new install scenario.

It would definitely be a good move if we could install plugins simply loading a list of uris/files. But I need to make sure this is stable and sufficiently spread in the community to implement that as a role's feature.

**Comment by marchenm** [comment]
Plugins that have documentation on the process:
* https://github.com/sonatype-nexus-community/nexus-repository-conda#easiest-install-beta
* https://github.com/sonatype-nexus-community/nexus-repository-conan/#easiest-install-beta

I've tested this personally and it worked for me.

**Comment by marchenm** [comment]
documentation on kar bundle installs: https://help.sonatype.com/repomanager3/bundle-development/installing-bundles

**Comment by vitkhab** [comment]
I assumed plugin installation would be helpful. Also many plugins already support building to *.kar bundle. And building to *.kar bundle is already implemented into org.sonatype.nexus.plugins:nexus-plugins.

So I've made a PR.
