### ISSUE TITLE
Add Truststore setting to LDAP groovy script

### ISSUE THREAD

**Issue by DerRooster** [ansible-ThoTeam/nexus3-oss#178]
On LDAP/AD connections using selfsigned certificates with the cert added to the Nexus Truststore it  is necessary to set the "Use Trustore" setting for the LDAP connection. There is currently no parameter to enable using the truststore in this ansible nexus3 role.

Nexus UI setting:
![image](https://user-images.githubusercontent.com/827163/60700363-fb077400-9f3a-11e9-86c7-5dee08a6ea84.png)

To enable the setting in the groovy script sonatype advises to use e.g. 
 ```
import org.sonatype.nexus.ldap.persist.*
import org.sonatype.nexus.ldap.persist.entity.*
import groovy.json.JsonSlurper
def ldap = new JsonSlurper().parseText(args)
def manager = container.lookup(LdapConfigurationManager.class.name)
manager.addLdapServerConfiguration(
  new LdapConfiguration(
    name: ldap.name,
    connection: new Connection(
      host: new Connection.Host(Connection.Protocol.ldap, ldap.host, ldap.port),
      maxIncidentsCount: 3,
      connectionRetryDelay: 300,
      connectionTimeout: 15,
      searchBase: 'ou=searchbase',
      authScheme: 'simple',
      systemPassword: 'systemPassword',
      systemUsername: 'systemUsername',
      useTrustStore: true
    ),
    mapping: new Mapping(
      ldapGroupsAsRoles: true,
      emailAddressAttribute: 'mail',
      userIdAttribute: 'uid',
      userMemberOfAttribute: 'memberOf',
      userObjectClass: 'inetOrgPerson',
      userPasswordAttribute: 'userPassword',
      userRealNameAttribute: 'cn',
      userBaseDn: ''
    )
  )
)

```
At this point I don't know if there is a setter for the truststore setting (I could not find any api docs for e.g. org.sonatype.nexus.ldap.*)

Please add / fix the TrustStore setting as it reverts every time the role gets executed.

**Comment by zeitounator** [comment]
Quickly implemented in above merged PR. You can now set this in your ldap config with `ldap_use_trust_store: true` .

The current integration test just shows that this new parameter does not break the script nor harm the very basic ldap mock test on travis. Can you please test that on your side and confirm it works as expected ? You can reopen the ticket if it doesn't. Thanks for your contribution.

**Comment by DerRooster** [comment]
Fantastic, thanks for the swift action :-)
I will let you know once I run into issues.
