### ISSUE TITLE
Problem with security in groovy script

### ISSUE THREAD

**Issue by Starfight** [ansible-ThoTeam/nexus3-oss#185]
I upgrade my Nexus to 3.18.1 today and I have a strange error with groovy script `setup_users_form_list.groovy` :
```
javax.script.ScriptException: groovy.lang.GroovyRuntimeException: Failed to create Script instance for class: class Script5. Reason: groovy.lang.MissingPropertyException: No such property: security for class: Script5
```

**Comment by zeitounator** [comment]
@Starfight: Sorry for the delay.

Can you try to force re-registration of scripts with `-e nexus_force_groovy_scripts_registration=true` and let me know if it fixes your problem ?

Thanks.

**Comment by Starfight** [comment]
The problem persist after force registration of script.

**Comment by zeitounator** [comment]
Are you using the latest version of the role ? (this should have been my first question).

**Comment by zeitounator** [comment]
@Starfight did you manage to fix your issue ?

**Comment by zeitounator** [comment]
Feel free to reopen if this is still not fixed.
