### ISSUE TITLE
Error to update repos

### ISSUE THREAD

**Issue by elevisse** [ansible-ThoTeam/nexus3-oss#186]
Hello,

In this file : [https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/files/groovy/create_repos_from_list.groovy](url) updates never happens.

Error is located between lines 119 and 133, in particular lines 125 to 132. This bloc actually is 
```
            if (configuration.equals(existingRepository.configuration)) {
                repositoryManager.update(configuration)
                currentResult.put('status', 'updated')
                log.info('Configuration for repo {} saved', currentRepo.name)
                scriptResults['changed'] = true
            } else {
                currentResult.put('status', 'no change')
            }

```
To make it work, i modified this by this bloc, simply :
```
            if (configuration.equals(existingRepository.configuration)) {
                currentResult.put('status', 'no change')
            } else {
                repositoryManager.update(configuration)
                currentResult.put('status', 'updated')
                log.info('Configuration for repo {} saved', currentRepo.name)
                scriptResults['changed'] = true
            }
```
Have a nice day and thanks for this public role.

**Comment by zeitounator** [comment]
Thanks for reporting. An exclamation mark that was lost along the way while refactoring all groovy scripts... Attached PR should be merged in a few minutes after CI completes. Cheers.

**Comment by zeitounator** [comment]
This is actually harder than expected. Work in progress.

**Comment by grundtinfo** [comment]
No problem, like I said, i resolved myself my case.

I have to say that I don't use your role in fact, i created my own to install Nexus in a k8s farm.
Cheers
