### ISSUE TITLE
How to exclude particular repository from the list of 4 repos being created

### ISSUE THREAD

**Issue by Jagdish0886** [ansible-ThoTeam/nexus3-oss#193]
Hey, thank you for the wonderful opensource projects,
I have crated a user, role and now trying to create the repos, it is creating 4 repos for me.
But i need to create just one maven2 hosted repo, how can i create the ONLY one, by excluding other. I tried to comment our the unwanted repos but its not successful e.g. it given below error please guide:

TASK [nexus : apply defaults to maven hosted repos] ********************************************************************************************************************
fatal: [centos]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'nexus_repos_maven_hosted' is undefined\n\nThe error appears to have been in '/app/playbook/roles/nexus/tasks/process_repos_list.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: apply defaults to maven hosted repos\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'nexus_repos_maven_hosted' is undefined"}

**Comment by zeitounator** [comment]
Hi and thanks for your interest.

For historical reasons, the role contains several maven repos as examples in the defaults: https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/defaults/main.yml#L254

You simply have to redefine the following vars in your playbook to override those defaults and have only the repos you need:
```
nexus_repos_maven_proxy: []

nexus_repos_maven_hosted:
  - name: your_hosted_repo
    # rest of your repo config here

nexus_repos_maven_group: []
```

**Comment by zeitounator** [comment]
Without any return, I consider the case closed.
