### ISSUE TITLE
Cannot create role on new repositories due to missing privileges

### ISSUE THREAD

**Issue by loganmzz** [ansible-ThoTeam/nexus3-oss#217]
Roles are created before repositories, so repository-specific privileges don't exist.

**Comment by zeitounator** [comment]
Hi @loganmzz,

This is already fixed on master. Please see #211 

I just finished an other PR and will tag a new release in a few hours after the merge.

**Comment by loganmzz** [comment]
Ok, nice !

**Comment by zeitounator** [comment]
New release is taged if you want to fix a version: https://github.com/ansible-ThoTeam/nexus3-oss/releases/tag/v2.4.5

**Comment by loganmzz** [comment]
Thank you very much, I have seen it and installation is already in progress on a sandbox ;)
