### ISSUE TITLE
Backup Nexus into S3?

### ISSUE THREAD

**Issue by benlei-gfm** [ansible-ThoTeam/nexus3-oss#226]
It would be great if there was a setting to also store backups onto AWS S3.

**Comment by zeitounator** [comment]
Hi @ben-lei-gfm and thanks for your interest. This would be a nice feature indeed but really not on my priority list for several reason:

* I think it is quite trivial to copy the existing backup directory to S3 from outside of nexus/this role.
* I cannot currently test anything related to S3 as I don't have an active AWS subscription nor took the time to setup [LocalStack](https://localstack.cloud/) for this kind of tests.
* My time to work on this project is limited and I focus primarily on fixing "bugs" related to new nexus versions and adding new possibilities to support new features in nexus.

So I'm not closing the door but it will not be on the todo list until I really get enough time and interest. In the meantime, if you want to contribute a PR for this, I'll be happy to look at it and merge it if the implementation is ok.

Cheers.

**Comment by ben-lei-gfm** [comment]
I'm not too familiar with how to setup s3 support, but I was able to get s3fs working on my instance. I'll create a PR for this.
