### ISSUE TITLE
backup.groovy.j2 error

### ISSUE THREAD

**Issue by sgommaraschi** [ansible-ThoTeam/nexus3-oss#228]
Hi ThoTeam guys,
I installed Nexus3 few week ago and i recently found an issue related to groovy backup script.
During executions it's fail executing this part of code 

    log.info("Wait for temporary db backup task to finish")
    while (tempBackupTask.currentState.state != TaskInfo.State.WAITING) {
        TimeUnit.SECONDS.sleep(1)
    }

with this log error 

2019-12-27 03:00:00,788+0100 INFO  [quartz-3-thread-19]  *SYSTEM org.sonatype.nexus.internal.script.ScriptTask - Wait for temporary db backup task to finish
2019-12-27 03:00:00,791+0100 ERROR [quartz-3-thread-19]  *SYSTEM org.sonatype.nexus.internal.script.ScriptTask - groovy.lang.MissingPropertyException: No such property: State for class: org.sonatype.nexus.scheduling.TaskInfo
Possible solutions: name
2019-12-27 03:00:00,793+0100 INFO  [quartz-3-thread-19]  *SYSTEM org.sonatype.nexus.internal.script.ScriptTask - Task complete

So the side effect is these parts of code are not probably executed

    log.info("Remove temporary task")
    tempBackupTask.remove()

    /** Post backup rotation */
    if (nexusBackupRotate && !nexusBackupRotateFirst) {
        rotateBackup()
    }

In fact temporary task still present if you look at Nexus Console and also folders on backup FS are not removed 

[root@nexprod01 nexus-backup]# du -sch *
912K    blob-backup-2019-11-23-03-00-00
760K    blob-backup-2019-11-24-03-00-00
760K    blob-backup-2019-11-25-03-00-00
824K    blob-backup-2019-11-26-03-00-00
2.7M    blob-backup-2019-11-27-03-00-00
4.8M    blob-backup-2019-11-28-03-00-00
7.0M    blob-backup-2019-11-29-03-00-00
7.1M    blob-backup-2019-11-30-03-00-00
7.1M    blob-backup-2019-12-01-03-00-00
7.1M    blob-backup-2019-12-02-03-00-00
192M    blob-backup-2019-12-03-03-00-00
256M    blob-backup-2019-12-13-14-10-19
256M    blob-backup-2019-12-14-03-00-00
256M    blob-backup-2019-12-15-03-00-00
256M    blob-backup-2019-12-16-03-00-00
295M    blob-backup-2019-12-17-03-00-00
294M    blob-backup-2019-12-18-03-00-00
294M    blob-backup-2019-12-19-03-00-00
294M    blob-backup-2019-12-20-03-00-00
294M    blob-backup-2019-12-21-03-00-00
294M    blob-backup-2019-12-22-03-00-00
294M    blob-backup-2019-12-23-03-00-00
294M    blob-backup-2019-12-24-03-00-00
294M    blob-backup-2019-12-25-03-00-00
294M    blob-backup-2019-12-26-03-00-00
294M    blob-backup-2019-12-27-03-00-00

![Capture00](https://user-images.githubusercontent.com/12333670/71520435-5b5cea00-28bc-11ea-91df-a220bfb77262.PNG)

![Capture01](https://user-images.githubusercontent.com/12333670/71520436-5b5cea00-28bc-11ea-8b21-e12a0da11153.PNG)
 
Nexus version  is 3.19.1-01

These are backup ansible settings

#
# Backups
#
nexus_backup_configure: true
nexus_backup_cron: '0 0 3 * * ?'
nexus_backup_dir: '/nexus/nexus-backup'
nexus_restore_log: '{{ nexus_backup_dir }}/nexus-restore.log'
nexus_backup_rotate: true
nexus_backup_rotate_first: false
nexus_backup_keep_rotations: 4  # Keep 4 backup rotation by default (current + last 3)

Thanks in advance for you support
Simone

**Comment by ben-lei-gfm** [comment]
I noticed the error too. See my pr which has a fix for it:
https://github.com/ansible-ThoTeam/nexus3-oss/issues/226

**Comment by zeitounator** [comment]
Hi all. This is probably related to an API change between version (as most of the time with yet stable groovy scripts). This seems to be fixed by above PR. I am currenlty reviewing all of them and wll merge as much as possible ASAP.
