### ISSUE TITLE
From Nexus 3.20 CreateContentSelector does not work

### ISSUE THREAD

**Issue by Koeppchen** [ansible-ThoTeam/nexus3-oss#230]
Using the Task results in 
You cannot create an instance from the abstract interface "org.sonatype.nexus.selector.SelectorConfiguration".
In https://github.com/sonatype/nexus-public/blob/master/components/nexus-selector/src/main/java/org/sonatype/nexus/selector/SelectorManager.java you can find a New Method to Create the Instance.
I have changed the groovy Code to 
`if (selectorConfig == null) {
    update = false
    selectorConfig = selectorManager.newSelectorConfiguration()
    selectorConfig.name =  parsed_args.name
}
`
But this will not work with Nexus < 3.20.

**Comment by zeitounator** [comment]
We have several problems currently being taken care of with the lastest 3.20 nexus version. They should hopefully being fixed soon. In the meantime, you can force the installation of the previous version with `nexus_version: 3.19.1-1`
