### ISSUE TITLE
[Poll] dropping support for older nexus versions ?

### ISSUE THREAD

**Issue by zeitounator** [ansible-ThoTeam/nexus3-oss#253]
For this ticket your should read "Help wanted" as "I'll be happy to get a response in comments" :) This is actually an idea after a code review / discussion started in #252.

I am considering dropping support for older versions of nexus in the role. The goal here is to know the point to go down in version history. There are currently several issues:
- Changes needed in groovy scripts to adapt to new version are not always backward compatible. Known issue: `create_cleanup_policies_from_list` will not function with nexus < 3.20 (although the role will work with older versions if you don't declare cleanup policies)
- There are several admin password routines depending on version (before and after 3.17)
- There is a path detection for restore dir (before and after version 3.11)
- There is a path detection for the script API endpoint (before and after version 3.8)
- There is a detection of list of application settings directories  (before and after version 3.1)

Appart from the groovy scripts, where we do not always have a real solution (considering moving to rest API for those which is only available in recent versions as well), I'd like to clean-up the code from too old version detections.

What is in your opinion the oldest version this role should support (e.g. dropping support code for versions prior to) ? Please click on your choice. Thanks in advance to all users who will answer

[![](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.1)](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.1/vote)
[![](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.8)](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.8/vote)
[![](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.11)](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.11/vote)
[![](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.17)](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/3.17/vote)
[![](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/Support%20for%20current%20and%20previous%20is%20enough)](https://api.gh-polls.com/poll/01E23RDNY75EJ0GKZF9QZR0H3S/Support%20for%20current%20and%20previous%20is%20enough/vote)

**Comment by wiget** [comment]
IMHO this role should support latest and one previous version of Nexus. This will be >= 3.20.0 currently.

**Comment by zeitounator** [comment]
Thanks to all who participated. The trend is now clear for me. Il will from now on focus on latest nexus version and gradually clean up the code from old version checks when possible.
