### ISSUE TITLE
Remove/disable default admin account

### ISSUE THREAD

**Issue by zeitounator** [ansible-ThoTeam/nexus3-oss#257]
In quite a few large companies with strict internal security policies, disabling default administration accounts on installed services/products/servers is a requirement. I am not discussing the relevance of such rules here, I just take it as a fact.

The role should allow to use an alternate management account for deployment/provisionning and should be able to remove/disable the default `admin` account on first install if required.

**Comment by Serienmorder** [comment]
So you want me to help with this? Do you want me to go about with the method I've been doing?

**Comment by zeitounator** [comment]
Sorry for the delays currently..... I actually already startted to work on this.
