### ISSUE TITLE
You cannot create an instance from the abstract interface 'org.sonatype.nexus.ldap.persist.entity.LdapConfiguration

### ISSUE THREAD

**Issue by onknows** [ansible-ThoTeam/nexus3-oss#258]
I have run into an issue with latest release that is very persistent,  troublesome and inexplicable.

I upgraded to latest release of Nexus using latest release of Ansible role. The upgrade went through my dev and staging environment but now fails in production.

So the exact same ldap config is valid for staging - which is identical to production - but fails in production.

`TASK [ansible-thoteam.nexus3-oss : Calling Groovy script setup_ldap] **************************************************** fatal: [myserver]: FAILED! => {"changed": false, "connection": "close", "content": "{\n  \"name\" : \"setup_ldap\",\n  \"result\" : \"org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:\\nScript1.groovy: 13: You cannot create an instance from the abstract interface 'org.sonatype.nexus.ldap.persist.entity.LdapConfiguration'.\\n @ line 13, column 18.\\n   def ldapConfig = new LdapConfiguration()\\n                    ^\\n\\n1 error\\n\"\n}", "content_length": "367", "content_type": "application/json", "date": "Fri, 06 Mar 2020 08:09:15 GMT", "elapsed": 0, "failed_when_result": true, "json": {"name": "setup_ldap", "result": "org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:\nScript1.groovy: 13: You cannot create an instance from the abstract interface 'org.sonatype.nexus.ldap.persist.entity.LdapConfiguration'.\n @ line 13, column 18.\n   def ldapConfig = new LdapConfiguration()\n                    ^\n\n1 error\n"}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "server": "Nexus/3.20.1-01 (OSS)", "status": 400, "url": "https://myserver:443/nexus/blobs/service/rest/v1/script/setup_ldap/run", "x_content_type_options": "nosniff"}`

Any ideas why this is not working? 

Actually I think it is not possible to manage an upgraded Nexus using this role. I upgraded from 3.7.1-02 to nexus_version: 3.20.1-01.

Instances that have this upgrade path cannot be managed using latest version of the role per error message above.

I don't understand why. I suppose it is a Nexus issue related to the inner working of Nexus. In an upgraded instance the role will still execute older scripts versions that are incompatible with latest release of Nexus.

Maybe SonaType should revisit the idea of using server side executed Groovy code as an "API". Using Nexus version dependent Groovy code as an "API" is maybe defeating the purpose of having an API. This way we are tied to the internal working of Nexus rather than a stable / managed interface aka what we would call an API.

**Comment by zeitounator** [comment]
Hi,

The ldap groovy script is a particularly problematic one. I inherited this script when I forked the role to take over maintenance (see role history in README). It is using internal implementation that are not even published. At that time there was no other option to automate provisionning. Since then, a lot of REST API endpoints have been published. I am planning to progressively move groovy scripts to REST API where this is more convenient.

Regarding your particular problem, I have the feeling that you are still using an older script for some reason. Please try again with `-e nexus_force_groovy_scripts_registration=true` to see if it fixes the issue.

**Comment by zeitounator** [comment]
Without any return, I'm closing this for now. Feel free to ask for re-opening if needed.

**Comment by sashasimkin** [comment]
I was using old version of the role, after upgrading to the latest version everything's cool :)
