### ISSUE TITLE
Molecule issue

### ISSUE THREAD

**Issue by francis2211** [ansible-ThoTeam/nexus3-oss#261]
Any Idea why I am getting this error when I run molecule? I am also getting the same error when I try to run ansible

TASK [nexus3-oss : Access scripts API endpoint with defined admin password] ****
fatal: [nexus3-oss-default]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "", "content_length": "1268", "content_type": "text/html; charset=utf-8", "elapsed": 0, "msg": "Status code was 404 and not [200, 401]: HTTP Error 404: Not Found", "pragma": "no-cache", "proxy_connection": "close", "redirected": false, "status": 404, "url": "http://localhost:8081/service/rest/v1/script"}

[10:50:20] $ docker ps
CONTAINER ID        IMAGE                                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
e256a8925066        thoteam/molecule_apache_openjdk8:centos7                        "/usr/sbin/init"         8 minutes ago       Up 8 minutes                            nexus3-oss-default
bafdb6c6f628        thoteam/slapd-server-mock:latest                                "/bin/bash /run.sh"      9 minutes ago       Up 9 minutes        389/tcp, 636/tcp    slapd-server-mock

**Comment by zeitounator** [comment]
Which version of nexus did you install in the container ? Is it the default ? (latest) ?

**Comment by francis2211** [comment]
Yes it’s is the latest.

**Comment by francis2211** [comment]
Yes I basically clone the repo install all the require package and ran
molecule converge... and it’s failing on the API part of it, it cannot hit
that url, but when I login to the container I can curl localhost:8081

**Comment by francis2211** [comment]
UPDATE:

If I login to the container (nexus3-oss-default) and I execute the following 
``
 [root@nexus3-oss-default /]# curl -v -X GET -u admin:364617bb-9a45-453d-94cd-6807c343a728 'http://localhost:8081/service/rest/v1/script'
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Server auth using Basic with user 'admin'
> GET /service/rest/v1/script HTTP/1.1
> Authorization: Basic YWRtaW46MzY0NjE3YmItOWE0NS00NTNkLTk0Y2QtNjgwN2MzNDNhNzI4
> User-Agent: curl/7.29.0
> Host: localhost:8081
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 18 Mar 2020 15:18:32 GMT
< Server: Nexus/3.21.1-01 (OSS)
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Content-Length: 104
< 
[ {
  "name" : "maven",
  "content" : "repository.createMavenHosted('private')",
  "type" : "groovy"
* Connection #0 to host localhost left intact


I think the role its not picking up the changeme password

**Comment by francis2211** [comment]
Ignore this, looks like it was and environment problem
