### ISSUE TITLE
Allow quota for blobstores

### ISSUE THREAD

**Issue by fabricat** [ansible-ThoTeam/nexus3-oss#273]
Neither in the documentation nor in the code seems possible to enable the "Soft Quota" option available in Nexus3 GUI.

Will this setting be integrated into this role?

**Comment by zeitounator** [comment]
It is not integrated at the moment but could be as a new feature. If you are willing to propose a PR for that, I'll be happy to review it.

**Comment by fabricat** [comment]
Thank you for your kind response.
I'd really like to help, but I am pretty new to Ansible :/

**Comment by Serienmorder** [comment]
I've got this. I'll work on a PR promptly.

**Comment by Serienmorder** [comment]
Functionality added in #287

**Comment by zeitounator** [comment]
Leaving openned for implementation to come.

**Comment by nliebelt** [comment]
Hey, 

we are also interested in having that feature. I am just a bit confused about the Status? 

> Functionality added in #287

This looks like a proposed change to me or what is the issue?

**Comment by Serienmorder** [comment]
zeitounator didn't want my implementation because it meant using an overloaded uri module and a lot of additional python to maintain.

**Comment by nliebelt** [comment]
Thx for the clarification @Serienmorder .

**Comment by fatemealizade** [comment]
how to add blobstores while creating a task scheduler with that groovy script?
