### ISSUE TITLE
Tagging tasks

### ISSUE THREAD

**Issue by fabricat** [ansible-ThoTeam/nexus3-oss#275]
Sometimes I need to apply the entire role, sometimes I need to re-run just the provisioning part and sometimes I need to run only the configuration tasks.

Instead of using the "nexus_run_provisionning" special variable, why not use the Ansible [Tags](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html) feature?
E.g. basic tags could be "installation", "provisioning" and "configuration".

Depending on the cases, this should make possible to run a subset of the tasks using either "ansible-playbook" parameters "--tags" or "--skip-tags" (or both).

**Comment by zeitounator** [comment]
Hi,

Please see #271
