### ISSUE TITLE
nexus_delete_default_repos not working when nexus_data_dir is mounted to external drive

### ISSUE THREAD

**Issue by pogosoftware** [ansible-ThoTeam/nexus3-oss#279]
Hello

I'm creating virtual machine with external data disk and mount nexus_data_dir to this drive. The problem is that it is ignoring the nexus_delete_default_repos variable.

Here is the gist that shows this issue:
https://gist.github.com/pogosoftware/88eb184c9cff2fc24d2f0ddb9c5b4d41

Also, the new blob store has the wrong path - instead of  'nexus_data_dir/blobs/apt' it is 'apt'.

Best regards
Przemyslaw

**Comment by zeitounator** [comment]
Is that data disk already populated with a pre-existing nexus install ?

**Comment by pogosoftware** [comment]
No. drive is empty - only ext4 partition is created.

**Comment by pogosoftware** [comment]
I figure it out. Empty drive with partition has a lost+found directory. I've created 
[PR 280](https://github.com/ansible-ThoTeam/nexus3-oss/pull/280) which will be ignoring listing lost+found directory.

This fix works for me.

**Comment by zeitounator** [comment]
Nice one ! I haven't been using ext[2-4] filesystems for years now so I totally missed it. Thanks ! I'm crafting a new version these days to introduce some changes I need on my own side. I will embark your PR with some others. Stay tuned.
