### ISSUE TITLE
how to schedule nexus backup in ubuntu server 

### ISSUE THREAD

**Issue by svilambi** [ansible-ThoTeam/nexus3-oss#291]
Hi,
How to configure schedule nexus backup in ubuntu server using crontab

https://github.com/ansible-ThoTeam/nexus3-oss/wiki/%5BSchedule-Type%5D-daily

Thanks in advance

**Comment by svilambi** [comment]
Hi Team,

how to configure schedule nexus backup in ubuntu server using crontab

https://github.com/ansible-ThoTeam/nexus3-oss/wiki/%5BSchedule-Type%5D-daily

Thanks in advance

**Comment by zeitounator** [comment]
Hi. What is unclear about the documentation above ? What is your current configuration ? Backups are configured with a cron expression by default.

To clear all misunderstanding, we are talking here about a cron expression to schecdule backup in nexus internal task manager. This is not a system cron.

**Comment by svilambi** [comment]
Hi @zeitounator  ,

How to create daily backup

Actual problem : Nexus nexus repository is taking a lot of disk space in ubuntu machine.

Proposed solution: To take daily backup of blobs and DB. store in other location such as S3 bucket or NAS location.

Nexus Repository is on ubuntu machine

want to use crontab to schedule job for daily backup

Do we have any scripts to take backup and restore please let us know

please suggest....

**Comment by zeitounator** [comment]
https://github.com/ansible-ThoTeam/nexus3-oss#backups

This is a basic backup procedure supported by this role. If you want to do this differently, you'll have to bake your own out of the role.
