### ISSUE TITLE
Don't set up remote authentication

### ISSUE THREAD

**Issue by ktreptow** [ansible-ThoTeam/nexus3-oss#292]
When i provision a proxy repository, the http authentication is configured as shown in the screenshot. Is this intended? In this particular case, I don't need to authenticate to a remote storage.
Maybe I just overlooked a way to configure this part? As in disabling http settings completely?

![remote_proxy_auth](https://user-images.githubusercontent.com/37484788/82238788-1eab9100-9938-11ea-9fb7-61fc003bc14b.png)

Thanks so much!

**Comment by zeitounator** [comment]
Authentication is set only if `remote_username` is not null. Note that setting it to an empty string could lead to the above result (although I did not test it before answering). You should make sure none of `remote_username` and `remote_password` are set on your proxy repository definition.

**Comment by ktreptow** [comment]
Yeah, i thought so too. I have kind of a weird behaviour right now. The initial setup of a remote repository produces the mentioned problem, the second run gets rid of it despite not changing any configuration whatsoever. Any ideas? I'm a little confused.
