### ISSUE TITLE
Missing role dependency: rsync

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-ThoTeam/nexus3-oss#306]
The role wants to sync scripts via Rsync, but it isn't installed as a dependency.

**Comment by zeitounator** [comment]
This is clearly listed in the [requirements in README](https://github.com/ansible-ThoTeam/nexus3-oss#requirements) with a particular error message inviting you to install rsync when it errors. This was all implemented in #143. This should be enough to fix the issue and you can add a role which installs rsync prior to running this one if your wish.

Rsync if very frequently available on OS out of the box and I cannot add every possible package dependency check: too much complexity regarding the different OS, performance impact...
