### ISSUE TITLE
Add possibility to add more http options to the vhosts file

### ISSUE THREAD

**Issue by TimVerbois** [ansible-ThoTeam/nexus3-oss#313]
For my customer, I used your ansible role, but we had an issue with slashed (/) that were not translated.  We could fix this with the following option in the vhosts file:

  AllowEncodedSlashes On

But, I cannot get this done via the role.  Can you add an option (maybe a list of extra lines that can be added to httpd).

I'm willing to participate to add things like this, but I don't know if this is allowed and if I can do this.

**Comment by zeitounator** [comment]
Related to #314. I will answer there.
