### ISSUE TITLE
add extra port forwards to the role

### ISSUE THREAD

**Issue by TimVerbois** [ansible-ThoTeam/nexus3-oss#314]
In nexus you can create repositories that listen to other ports.  These ports are not exposed by the httpd.  

I created my own role that added that, but this is silly.  Can this be added to this role?  

Again, I'm willing to contribute myself and add this functionality to the role.

**Comment by zeitounator** [comment]
Hi @TimVerbois,

Thanks a lot for your interest and for your feature requests. To be clear from start, I will not include an implementation for this nor your other request in #313 in this role.

Now you definitely deserve a clear explanation of my position. Moreover I have some info to point you in the right direction to fix both of those issues cleanly, using the unmodified current role and your specific setup in a sustainable and easily maintainable way. I personally use this role to deploy and maintain daily a 1,5TB nexus installation which has quite a few repos (400+) including npm (needing `AllowEncodedSlashes` on apache as pointed out in https://issues.sonatype.org/browse/NEXUS-11630) and docker registries (configured on different ports and needing specific vhost in apache).

But I don't have time do that correctly and extensively jumping out of bed this morning. So please take this as a first quick answer and stay tuned for more. I promise to give a complete feedback over the week-end.

Cheers.

**Comment by zeitounator** [comment]
Sorry for the delay but my WE and beginning of week did not go as expected. And I suddenly remembered I made a previous answer that more or less explains what I wanted. Can you please have a look at this: https://github.com/ansible-ThoTeam/nexus3-oss/issues/34#issuecomment-355214121

My view has changed on what this role should take in charge but the recipe explained (child role with custom configs for apache) is the way to go. Over time, I have found that when you start touching to the reverse proxy rules, you usually have to configure things as close as possible to your environment (VIP, other RPs along the way, specific ip/host rules...). So I  think the role should now focus on deploying and provisionning nexus only. I leave the simple apache RP as an example for now, but anything that goes beyond that should be taken in charge with specialized user templates that I cannot maintain myself.

Please let me know if this more or less puts you in the correct direction. I'll try to give you more details if needed.

Once again, thanks for your interest.
