### ISSUE TITLE
 The error was: The input data is not valid. It does not contain the key 'json'. Is it a var registered from a uri: module call ?

### ISSUE THREAD

**Issue by suresh4test** [ansible-ThoTeam/nexus3-oss#325]
We are getting this error while using call_script.yml and tag we are using is v2.4.13 . I had seen, this error fixed in earlier version but still failing this.

{"msg": "The conditional check 'script_run | nexus_groovy_changed | bool' failed. The error was: The input data is not valid. It does not contain the key 'json'. Is it a var registered from a uri: module call ?"}

{"msg": "The conditional check 'script_run | nexus_groovy_details == 'Global script failure'' failed. The error was: The input data is not valid. It does not contain the key 'status'. Is it a var registered from a uri: module call ?

**Comment by nntk** [comment]
I get the same error but only while in a jenkins CI environment with idempotency enabled in the molecule toolset docker container. The fix from #267 doesn't seem to work for idempotency for me.

debian:buster is my target

**Comment by olakunleoladimeji** [comment]
I alo get have the same error on a Debian buster target. 

any workarounds?

**Comment by zeitounator** [comment]
Hi @suresh4test  @nntk @olakunleoladimeji 

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other projects while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

---
Are you still having this issue? I never came accoss it... If yes, could you please give more details:
- your ansible version
- this role version
- nexus version
- the task were this error happens
- if you can get this running with `-vvv`, the content of the API response

Thanks.

**Comment by zeitounator** [comment]
@suresh4test @nntk @olakunleoladimeji I actually found a situation where this happens. It is possible to get more info by running the role with `-vvv`. In my situation, it happened when provisioning nexus from scratch with a quite large number of repos (over 300). In that case nexus processes everything as expected but by the time the answer is returned, the `uri` module has reached the default 30s timeout, the task errors, and the custom filter does not find any json content to parse.

To see if you have the same problem you can run as advise above which willl show timeout was reached. You can then check the nexus_requests logs where you should see that nexus eventually replied with an http/200 status but after timeout was reached.

I just pushed a PR which I'll merge as soon as CI succeeds. This will automatically close this ticket. Please reply and tag me if this does not fix the issue for you.
