### ISSUE TITLE
Don't include default created raw/docker repos

### ISSUE THREAD

**Issue by mykelalvis-rialtic** [ansible-ThoTeam/nexus3-oss#328]
[This](https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/defaults/main.yml#L433-L450) and others cause my instance to have repos that I don't want if I activate `raw`, etc.

I'm not entirely clear about why they're here, and I don't know how to get them not to be present.

**Comment by zeitounator** [comment]
@mykelalvis-rialtic there are default example repositories declared in [default/main.yml](default/main.yml). For raw repositories as this is you example here is the snippet defining the defaults:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/3b3b46a53a65f0fa433b4215e60903d14002bfe5/defaults/main.yml#L436-L453

So if you set `nexus_config_raw: true` without any further changes, those default repositories will be created. If you don't want any of these, the best solution is to simply set `nexus_config_raw: false` which is the default. Note that this does not disable raw repos in nexus. It just tells the role to skip all tasks related to setting them up.

An other solution is to set your own list of repos which can be empty so basically the following:
```yaml
nexus_config_raw: true
nexus_repos_raw_proxy: []
nexus_repos_raw_hosted: []
nexus_repos_raw_group: []
```
will have the same effect as if configuring raw was disabled.

I admit that setting default repos to create can be misleading and I'm considering dropping entirely those definitions in a future release do default to empty lists everywhere. The initial goal was to document the different repo options but this can be moved to the README, in a doc directory or even in the wiki.

Let me know (even if I'm more than late, see my comment on your other question....) if this answers your concerns.

Thanks

**Comment by zeitounator** [comment]
Closing this for now as I'm quite sure the concern has been addressed.

**Comment by mykelalvis** [comment]
@zeitounator I haven't used this in months and months, but will likely do so soon.  I expect that you're right about both issues.  If I find disparity, I'll reopen, etc.  Thanks!
