### ISSUE TITLE
Scheduled tasks should be modified when they exists

### ISSUE THREAD

**Issue by zeitounator** [ansible-ThoTeam/nexus3-oss#33]
When the role is replayed for provisionning, schedulled tasks are systematically deleted and recreated.

We should have them modified when they already exists.

A step further: we should only modify them when their attributes have changed

A step in the future: we should have the api call return "changed" when a task is created/updated and ok 
when the task was left untouched.

**Comment by dannyk81** [comment]
I had the same idea about this, and have come up with this:

```
import groovy.json.JsonSlurper
import org.sonatype.nexus.scheduling.TaskConfiguration
import org.sonatype.nexus.scheduling.TaskInfo
import org.sonatype.nexus.scheduling.TaskScheduler
import org.sonatype.nexus.scheduling.schedule.Schedule

parsed_args = new JsonSlurper().parseText(args)

TaskScheduler taskScheduler = container.lookup(TaskScheduler.class.getName())

TaskInfo existingTask = taskScheduler.listsTasks().find { TaskInfo taskInfo ->
    taskInfo.name == parsed_args.name
}

if (existingTask && existingTask.getCurrentState().getRunState() != null) {
    log.info("Could not update currently running task : " + parsed_args.name)
    return
}

TaskConfiguration taskConfiguration = taskScheduler.createTaskConfigurationInstance(parsed_args.typeId)
if (existingTask) { taskConfiguration.setId(existingTask.getId()) }
taskConfiguration.setName(parsed_args.name)
taskConfiguration.setEnabled(parsed_args.enabled)

parsed_args.taskProperties.each { key, value -> taskConfiguration.setString(key, value) }

if (parsed_args.task_alert_email) {
    taskConfiguration.setAlertEmail(parsed_args.task_alert_email)
}

Schedule schedule = taskScheduler.scheduleFactory.cron(new Date(), parsed_args.cron)

taskScheduler.scheduleTask(taskConfiguration, schedule)
```

The above will use the ID of the existing task to update it (instead of Delete/Create), also I have changed the way the script handles tasks that are running during provisioning: instead of throwing an exception and failing the whole run, the issue is logged and the specific task is skipped.

Let me know what you think, if you think this is a good starting point we can make a PR for this.

**Comment by zeitounator** [comment]
That looks good ! Just don't forget to integrate the new [`parsed_args.booleanTaskProperties.each`](https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/files/groovy/create_task.groovy#L28) introduced in v2.0 (mainly for checkboxes)

I was wondering if we should go further. The call to any api uri currently just returns a "ok" in ansible whatever was done. It would be a good practice if we could get a "changed" when something was actually changed and "ok" only if nothing was changed.

The problem is that, since this is taken care of in [`call_script.yml`](https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/call_script.yml), if we try to fix this for tasks, we need to fix it for every other api call (at least that's how I see it from memory). So we might wait a bit for that unless you come up with some easy trick ;)

For existing tasks/repos this would also require to check each property against its current value in nexus and I'm still not sure the expected benefit is worth the hassle... I'd be interested to get your opinion.

Cheers.

**Comment by dannyk81** [comment]
> That looks good ! Just don't forget to integrate the new parsed_args.booleanTaskProperties.each introduced in v2.0 (mainly for checkboxes)
Indeed! I'll change this accordingly.

With regard to your other point, I have been pondering over it for quite some time, even starting doing something but eventually dropped it as I wasn't convinced about the value it will bring... I'll try to give it some more thought.

**Comment by zeitounator** [comment]
Hi. I just created a dev_2.1 branch for the next release. Please make the pull request against this branch. I'll merge everything at once into master when the release is finalized. Cheers.

**Comment by zeitounator** [comment]
Hi @dannyk81. Has you may have seen above, I already merged your changes on dev. I didn't have much time this month, and since there were no blocking/bug issues, I will give myself some more time to publish version 2.1 which I initially scheduled for tomorrow. I hope you don't mind. You can still use the dev_2.1 branch until I release to master. Cheers.

**Comment by dannyk81** [comment]
@zeitounator no worries, take your time!
