### ISSUE TITLE
Deleting default repos did not actually happen

### ISSUE THREAD

**Issue by mykelalvis-rialtic** [ansible-ThoTeam/nexus3-oss#330]
I set 

```
.....
vars:
    nexus_delete_default_repos: true
```
and it didn't remove the default repos.  

![image](https://user-images.githubusercontent.com/71276964/126990864-568a7c95-968d-4f35-9cf5-a630fbd011ed.png)

I think it might be something to do with `(nexus_data_dir_contents.stdout | length == 0) and` on [this line](https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/main.yml#L63), since it noted `skipping` each time.  However, I wasn't able to perform any deeper inquiry.

**Comment by mykelalvis-rialtic** [comment]
When I remove `(nexus_data_dir_contents.stdout | length == 0)` from the conditional, it works.  It appears that that conditional statement doesn't produce the expected output.  I imagine it worked previously, but then Something Changed™?

**Comment by shurikg** [comment]
From doc

```
Delete the repositories from the nexus install initial default configuration. This step is only executed on first-time install (when nexus_data_dir has been detected empty).
```

Does your nexus_data_dir is empty ?

**Comment by mykelalvis-rialtic** [comment]
I'm assuming it is not, since it seems like the conditional causes that resource not to fire.  This occurs during the initial install of Nexus with this playbook, so I don't think I have any way to ensure the directory *not* be empty at that point.

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

---

This is a missunderstanding. It did happen (there are much more that just 4 maven type repos by default) but the default maven declared in the role were created. Make sure you have `nexus_config_maven: false` in your configuration. Moreover, please try (later in the afternoon) as I'll push an enhancement to check the empty data directory + one to allow installing without any repository configured. Let me know if you still have the issue.

Once again, sorry for the tremendous delay.

**Comment by zeitounator** [comment]
Closing this for now as I'm quite sure the concern has been addressed.
