### ISSUE TITLE
the nexus_installation_dir under root privileges 

### ISSUE THREAD

**Issue by shurikg** [ansible-ThoTeam/nexus3-oss#336]
After installation the ```{{ nexus_installation_dir }}``` folder and files in it under root privileges.

Expected that ```{{ nexus_os_user }}``` user will be owner of all installation files.

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

----

This is actually wanted. `{{ nexus_os_user }}` has full control over the `{{ nexus_data_dir }}` but should not be able to change the installation files.
