### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by chkpnt** [ansible-ThoTeam/nexus3-oss#337]
As the content of this repository is GPL licensed I'm concerned: Would it be a license violation if I use parts of this repo (i. e. the groovy scripts) with modifications in an internally used playbook? (I can't license my playbook under GPL.)

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

----

The intended use of the scripts seems totally compatible with GPL. I hope you did not wait for this comment to go on...

Thanks for your kind concern.
