### ISSUE TITLE
Archive scripts - permission error with multiple users

### ISSUE THREAD

**Issue by AJDurant** [ansible-ThoTeam/nexus3-oss#342]
The 'Archive scripts' task writes a file to the systemwide /tmp/ dir, with write permissions for the user running it. On a system where multiple users my run ansible, this task gets permission denied for overwiting this file.

https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/nexus_install.yml#L517-L524

Perhaps there could be another `run_once` task beforehand with `become` to remove any pre-existing file?

**Comment by zeitounator** [comment]
I think a better approach would be to push that file inside `{{ nexus_dowload_dir }}` and that user on a shared system set it to their own ci/test/deployment dir. If we delete the files created by others as root, there could potentially be a concurrency issue: you could delete the file an other user just created and fail his running playbook. Does that look like an acceptable solution ?

**Comment by AJDurant** [comment]
Yeah, that would work, or just default to a user based tmp dir.

**Comment by zeitounator** [comment]
@AJDurant I'll work something out for the next release.
