### ISSUE TITLE
Using vault variables in apt repo fails to create repo

### ISSUE THREAD

**Issue by AJDurant** [ansible-ThoTeam/nexus3-oss#346]
I'm trying to configure an apt repo, and using ansible vault to encrypt my keypair and passphrase, but this causes Nexus to error, as the variables are not decrypted.

eg config:
```yaml
nexus_repos_apt_hosted:
  - name: apt-internal-focal
    distribution: focal
    keypair: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      30633533356239396165343162363565396563333766323831346461636236313461396135643639
      ...
    passphrase: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62313366646634343334623437646136396131306531306531316465663863313763313965303964
      ...
```

Results in:
```
2022-02-03 14:16:40,460+0000 INFO [qtp1671834476-3474] admin org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Creating repository: apt-internal-focal -> OrientConfiguration{repositoryName='apt-internal-focal', recipeName='apt-hosted', attributes={storage={blobStoreName=apt, strictContentTypeValidation=true, writePolicy=ALLOW_ONCE}, apt={distribution=focal}, aptSigning={keypair={__ansible_vault=****}, passphrase={__ansible_vault=****}}}}
2022-02-03 14:16:40,486+0000 ERROR [qtp1671834476-3474] admin org.sonatype.nexus.repository.manager.internal.RepositoryImpl - Failed to validate facet: org.sonatype.nexus.repository.apt.internal.gpg.AptSigningFacet$$EnhancerByGuice$$906138703@4b46cd34
java.lang.IllegalArgumentException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.sonatype.nexus.repository.apt.internal.gpg.AptSigningFacet$Config["keypair"])
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4236)
...
```

Specifically: ` aptSigning={keypair={__ansible_vault=****}, passphrase={__ansible_vault=****}}`

This seems to be caused by the redirection of variables
https://github.com/ansible-ThoTeam/nexus3-oss/blob/0c6c4a4f4331a4b19287d4f488552778825bfd41/tasks/main.yml#L142
and 
https://github.com/ansible-ThoTeam/nexus3-oss/blob/0c6c4a4f4331a4b19287d4f488552778825bfd41/tasks/call_script.yml#L14

This Ansible issue covers `to_json`: https://github.com/ansible/ansible/issues/76334

looks like it needs `vault_to_text=True` until that fix goes into main

**Comment by AJDurant** [comment]
Also affected by:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/0c6c4a4f4331a4b19287d4f488552778825bfd41/tasks/process_repos_list.yml#L443-L448

**Comment by lynxnot** [comment]
We have been encountering this bug too with yum and maven repos, with ansible 2.9 running on AWX.

When trying to create a yum proxy repository with a vault password, a wrong json model is injected in the database regardless of the exception. This caused our Nexus to refuse to restart because it could not validate the repository object. I have spent all day yesterday with Sonatype support and had to manually edit the database to restore the service.

With maven repos, the password is still not correct but at least the repository attributes are not corrupted in the database.

This is an example of the authentication object found in Nexus OrientDB :
```json
{
  "password": {
    "__ansible_vault": "$ANSIBLE_VAULT;1.1;AES256........"
  },
  "type": "username",
  "username": "user"
}
```
`password` is an object instead of a simple string and its inner value is in vault encrypted format.

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

----

This seems to have made it way into ansible main while I was "asleep": https://github.com/ansible/ansible/pull/76349

I'll close this but please let me know if there is still an issue with this. Thanks.
