### ISSUE TITLE
Add ability to add more groovy scripts

### ISSUE THREAD

**Issue by davidcallen** [ansible-ThoTeam/nexus3-oss#347]
Would be useful to have a new parameter like "custom_groovy_scripts", so a user of this role can pass additional scripts to the role to be registered into Nexus.

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.
----
You can quite easily do that in a children role by using the existing task file from this role. Moreover, the global path is to stop using groovy script and it is quite possible that nexus totally drop that possibility in the future (after making them disabled by default already a while ago).

My long term project (no schedule yet) is to transform this role into a collection and drop the current groovy scripts to use the API for everything (those script have actually proven to be a pain to maintain on some occasion in the past).

So, sorry, but I'll have to answer no on that feature.

Thanks for using this role.
