### ISSUE TITLE
Fix properties for Docker task on the Wiki

### ISSUE THREAD

**Issue by fabricat** [ansible-ThoTeam/nexus3-oss#350]
The [Docker - Delete unused manifests and images](https://github.com/ansible-ThoTeam/nexus3-oss/wiki/%5BTask-Type%5D-Docker-%7C-Delete-unused-manifests-and-images) page lacks the `deployOffset` task property, which was introduced with [NEXUS-26732](https://issues.sonatype.org/browse/NEXUS-26732).

The description of that parameter should be as follows.
```
  deployOffset:
    type: string
    description: Deploy offset in hours (manifests and images deployed within this period before the task starts will not be deleted)
```
An example could be:
```
...
    taskProperties:
      repositoryName: *
      deployOffset: "6"
...
```

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

Thanks for the information. I edited the corresponding page. Cheers.
