### ISSUE TITLE
Nexus Ansible role is failing to unpack downloaded nexus 

### ISSUE THREAD

**Issue by tomararobin** [ansible-ThoTeam/nexus3-oss#352]
While running nexus ansible role : 
**role**  : [ansible-thoteam.nexus3-oss] 
**version** : 2.4.15 [latest]
We are getting the below error : 

_TASK [ansible-thoteam.nexus3-oss : Unpack Nexus download] **********************
11:15:57  fatal: [nexus_host]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/nexus-3.34.1-01-unix.tar.gz\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" could not handle archive. Command \"/bin/unzip\" could not handle archive."}_

and we have **gtar**  and **unzip** installed on our vApp. 

After investigation we found that with **ansible version [2.9.5]** and **rhel version [8.3]**, we are able to execute this task, 
but with **ansible version : [2.9.27]** and **rhel version : [8.5]** facing above issue.

So role needs to be changed : by adding _**extra-ops**_  to **unarchive** module of unpack nexus download task.

**Reference** :
https://stackoverflow.com/questions/58792859/ansible-unarchive-command-causes-error-failed-to-find-handler

**Question** : 
Please assist in providing a solution that we can use or ; 
If you can provide needful changes in the role itself in next release of role.

**Comment by komalkumbh** [comment]
Facing same issue even if ansible version : 2.9.5 with same description mentioned by  [tomararobin]

Plz update on this issue

**Comment by zeitounator** [comment]
Hi.  
  
I'm getting back to maintenance after a long pause for 3 main reason: 1) I was quite busy on other projects while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain. Sorry for not getting in touch sooner.

As mentionned in my above paragraph (pasted to several users while I'm cleaning up left-over issues and PRs), this has been working like a charm for the last months with several nexus upgrades on centos 7, debian and ubuntu with updated versions of ansible. Make sure you have tar and gzip installed on the target. Update to a supported version of ansible: 2.9 is unmaintained for a long time now and the officially recommended/supported install method is `pip install ansible` which will get you the latest version.

Thanks for getting in touch and once again sorry for not replying sooner.
