### ISSUE TITLE
How can I set values for create_task.groovy?

### ISSUE THREAD

**Issue by fatemealizade** [ansible-ThoTeam/nexus3-oss#367]
Hi, I'm new to groovy and using these scripts in nexus
can anyone help me to pass args to these groovy files?

**Comment by zeitounator** [comment]
All scripts are expecting a json payload sent as POST as shown in the global `call_script.yml` task file

https://github.com/ansible-ThoTeam/nexus3-oss/blob/3925e65d0dcb0d57086af53131d85b889da5da21/tasks/call_script.yml#L2-L25

For this particular script you can find an example expected payload in the [wiki](https://github.com/ansible-ThoTeam/nexus3-oss/wiki/Scheduled-tasks-configuration). You can also simply read the script to see the expected parameters.
