### ISSUE TITLE
Allowing anonymous docker pull

### ISSUE THREAD

**Issue by NormanJS** [ansible-ThoTeam/nexus3-oss#370]
Hello, Nexus 3.46 has an option for anonymous pulls from a docker repository, though I don't see any way to do this with this role.

Here's how it looks on the Web UI:
![Nexus Anonymous Docker Pull)](https://user-images.githubusercontent.com/83409549/216778857-88a8b1e4-0a97-49dd-bdac-d6ff965268b3.png)

Is it unsupported, or is it just undocumented?

**Comment by zeitounator** [comment]
This has been an option in nexus for years, far before version 3.46 and configuring it is indeed supported.

Prereq 1: you need to allow anonymous access to your nexus instance. See https://github.com/ansible-ThoTeam/nexus3-oss#default-anonymous-access
Prereq 2: docker bearer token realm must be enabled. See https://github.com/ansible-ThoTeam/nexus3-oss#blobstores-and-repositories at the end of the section.
Prereq 3: docker configuration must be enabled for the role (same link as above)

Then you can then define a registry in any of the `nexus_repos_docker_[hosted|proxy|group]` lists. You can look at the examples in `defaults/main.yml`. The only misleading detail is that `Allow anonymous pull` translates internally in nexus to `forceBasicAuth = false`. Here is an example for a hosted repo with anonymous pull enabled:

```yaml
nexus_repos_docker_hosted:
  - name: my_private_repo
    http_port: 9901
    v1_enabled: false
    force_basic_auth: false
```
