### ISSUE TITLE
Add the ability to configure the "Allow subdomain routing" for docker repos.

### ISSUE THREAD

**Issue by RWWesselink** [ansible-ThoTeam/nexus3-oss#376]
I would like to be able to configure the value of the "Allow subdomain routing" for docker repos with ansible and this playbook. Currently this is not possible.

![image](https://github.com/ansible-ThoTeam/nexus3-oss/assets/10417924/09a5c8cb-f30f-435a-8b9a-55540b54758c)

**Comment by brianveltman** [comment]
Hi team mate see #390

**Comment by brianveltman** [comment]
Closed. Fixed and merged in #390
