### ISSUE TITLE
Add parameters auto-block and http-request setting in repos

### ISSUE THREAD

**Issue by KevinJoaquim** [ansible-ThoTeam/nexus3-oss#378]
Hi, 

I would like to customize auto-bloc and the http-request settings in my proxy repos.

Like this : 
![image](https://github.com/ansible-ThoTeam/nexus3-oss/assets/8696431/721d424b-049c-4b0e-a6ee-974be0a1bba1)

Is it possible to add ansible variables?

**Comment by brianveltman** [comment]
@KevinJoaquim pending PR #394
