### ISSUE TITLE
Unable to set Layout Policy for yum repositories

### ISSUE THREAD

**Issue by TylerAvocat** [ansible-ThoTeam/nexus3-oss#380]
Setting the attribute layout_policy for yum repo seems to have no effect.

Looking at the file [create_repos_from_list.groovy](https://github.com/ansible-ThoTeam/nexus3-oss/blob/main/files/groovy/create_repos_from_list.groovy), the layout_policy ends up populating the layoutPolicy field int the repo config.

Looking at nexus code, it should populate deployPolicy field rather than layoutPolicy field.

**Comment by brianveltman** [comment]
It's fairly easy to add this. I can do this somewhere this week if you still need it.

**Comment by brianveltman** [comment]
@TylerAvocat pending PR #392
