### ISSUE TITLE
Add a parameter allow_redeploy_latest_tag to nexus_repos_docker_hosted

### ISSUE THREAD

**Issue by xaviou** [ansible-ThoTeam/nexus3-oss#385]
Since Nexus [3.21.1](https://help.sonatype.com/repomanager3/product-information/release-notes/2020-release-notes#id-2020ReleaseNotes-Docker.4) there is a new parameter "Allow redeploy only on 'latest' tag" for hosted docker repositories with deployment policy "Disable redeploy":

![Screenshot_20231107_170256](https://github.com/ansible-ThoTeam/nexus3-oss/assets/1102034/6fb7d197-5166-48d1-ac2f-48cda0e9f9e2)

Because we cannot set this parameter through Ansible we get [this error](https://stackoverflow.com/questions/42907903/allow-redeploy-for-latest-docker-tag-in-nexus-oss).

**Comment by brianveltman** [comment]
@xaviou work in progress :-)

**Comment by brianveltman** [comment]
@zeitounator PR is ready #395
