### ISSUE TITLE
Poll: Which ansible version are you using ?

### ISSUE THREAD

**Issue by zeitounator** [ansible-ThoTeam/nexus3-oss#53]
Hi users and thanks for your interest !

I'm questioning myself for the future releases on which ansible minimum version we should support for this role. My overall view is that it is quite easy to get the latest ansible version via `pip install`, either globally or through a python virtualenv. If I only listen to myself, I would then move to latest version.

Meanwhile, some of you might not be able to run ansible 2.4, either because of server access restriction or because of other roles you are using requiring an older version.

In order to take an enlighten decision, could you please answer the following questions:
- Which ansible version are you currently using ?
- if answer above is either `2.2` or` 2.3`, would you be ok if we switch requirements to the latest available ansible `2.4` ?
- if answer above is no, would you be ok to switch requirements to ansible `2.3` ?

Thanks in advance for your answers.

**Comment by apocalypskmaw** [comment]
>Which ansible version are you currently using ?

version `2.4.3`

>if answer above is either 2.2 or2.3, would you be ok if we switch requirements to the latest available ansible 2.4 ?

yes

**Comment by wiget** [comment]
I'm using latest 2.4.

**Comment by dawud** [comment]
Latest for me means `2.5.0`

```
$ ansible --version                  
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

**Comment by sesturm** [comment]
I use the latest version (2.5.0) from the Docker image williamyeh/ansible:centos7

**Comment by zeitounator** [comment]
From the returns I got so far, looks like I can safely move on for a 2.4 minimum version. I will get on this as soon as I return from vacations in 2 weeks.

**Comment by zeitounator** [comment]
Thanks to everyone who took the time to respond. As indicated in the [latest release](https://github.com/ansible-ThoTeam/nexus3-oss/releases/tag/v2.1.3), we will start supporting the latest ansible version by default starting with version 2.2.0.
