### ISSUE TITLE
Calling Groovy script update_admin_password step fails when upgrading to 3.10.0-04

### ISSUE THREAD

**Issue by 030** [ansible-ThoTeam/nexus3-oss#64]
Perhaps this is already known, but I just updated to 3.10.0-04 and there is a failure in:

Calling Groovy script update_admin_password

```
HTTP Error 405: HTTP method POST is not supported by this URL", "pragma": "no-cache", "redirected": false, "server": "Nexus/3.10.0-04 (OSS)", "status": 405, "url": "http://localhost:8081/service/siesta/rest/v1/script/update_admin_password/run", "x_content_type_options": "nosniff"
```

Either this step should be skipped or run successful.

When the default version, i.e. nexus_version: '3.9.0-01' is used again the script succeeds.

**Comment by zeitounator** [comment]
Thanks for reporting. I did not yet try to bump to latest nexus version. Will do that when returning from vacation in 2 weeks.

In the mean time, if you find a solution, a PR is very welcome :)

**Comment by Brialius** [comment]
Hello @zeitounator @030 ,
This issue related to incorrect version detection:

```
changed: [localhost] => (item=/opt/nexus-3.10.0-04)
TASK [ansible-ThoTeam.nexus3-oss : Get rest API endpoint (v < 3.8.0)] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible-ThoTeam.nexus3-oss : Get rest API endpoint (v >= 3.8.0)] **********************************************************************************************************************************************************************
skipping: [localhost]
```

I've fixed this issue by using `when: "{{ nexus_version is version_compare('3.1.0', '<') }}"` instead of straight string comparison `when: nexus_version < '3.1.0'`

It works with `3.10.0-4` but I had no chance to proper test this fix with different tests

**Comment by Brialius** [comment]
#65

**Comment by zeitounator** [comment]
Thanks! As mentionned above, will see this when I'm back.

**Comment by deveth0** [comment]
I just tried your fix, looks great, thank you!
