### ISSUE TITLE
Running Sonatype Nexus in Docker

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-ThoTeam/nexus3-oss#86]
I'd like to run this in Docker.

**Comment by zeitounator** [comment]
Well technically you can since all travis tests are running in Docker containers. But this would not be suited for production as the image needs to be ran privileged with systemd enabled inside.

I have a plan to separate the nexus install part from the provisioning tasks, probably by splitting this into two separate roles. But I have no ETA for this on my side as this not a priority for now.

I keep this open with the pending label to add it to a next release.

**Comment by AndrewCooper** [comment]
I'm interested in this as well. I wonder if it would work to set up a container with Java (for nexus) and Python (for ansible), and run the role against this container using the docker connection plugin, as described at https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#non-ssh-connection-types

I have not yet attempted this, but it seems like it would work.

**Comment by bbaassssiiee** [comment]
There are images, like this one:

```
docker pull sonatype/nexus3:3.10.0@sha256:536b1d0a28e85626cfe44929ba44f76f29dd99c68e25be993c0e69d3f7d6f30b
```

It would be useful to customize that.

**Comment by zeitounator** [comment]
@AndrewCooper. as stated in my comment in june, it definitely works ! Have a look at the molecule tests, this is exactly what it is doing using a base image with only java and apache installed.

**Comment by bbaassssiiee** [comment]
the image stated above runs as user nexus

**Comment by psharkey** [comment]
> Well technically you can since all travis tests are running in Docker containers. But this would not be suited for production as the image needs to be ran privileged with systemd enabled inside.
> 
> I have a plan to separate the nexus install part from the provisioning tasks, probably by splitting this into two separate roles. But I have no ETA for this on my side as this not a priority for now.
> 
> I keep this open with the pending label to add it to a future release.

@zeitounator Would you be open to a PR which runs this without privileged mode and systemd enabled? The changes look to be isolated to https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/nexus_install.yml. It would be nice to use the same role with the [sonatype/nexus3
](https://hub.docker.com/r/sonatype/nexus3) Docker image. An additional molecule test would be needed as well, correct?

**Comment by zeitounator** [comment]
@psharkey Sorry for the delay in my response. I am going to look with much interest at your PR.
