### ISSUE TITLE
Support s3 blob stores

### ISSUE THREAD

**Issue by jimbeck** [ansible-ThoTeam/nexus3-oss#87]
S3 backed blob stores was added to nexus 3.12.
Are you able to create an s3 backed blob store given the current implementation?

**Comment by zeitounator** [comment]
@jimbeck not yet. Unless I'm wrong, it should be fairly easy to implement modifying https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/files/groovy/create_blobstore.groovy. I'll try to embark this for the next release. If you want to submit a PR for that you're welcome
