### ISSUE TITLE
Add support for creating repos with apt format

### ISSUE THREAD

**Issue by internaught** [ansible-ThoTeam/nexus3-oss#88]
It'd be great if apt repo creation were supported.

**Comment by zeitounator** [comment]
@internaught you should direct this request to sonatype. Nexus3 does not support apt repository format for now. I'd be happy to implement it in the role once they support it

**Comment by wiget** [comment]
It's supported by open source plugin: https://github.com/sonatype-nexus-community/nexus-repository-apt

**Comment by zeitounator** [comment]
The goal here is to support the stock version. I'll add support if sonatype includes this functionality as a core plugin. Sorry but I don't have enough time to maintain the inclusion of third party plugins.
